name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.39.2
        cache: true
        # auth-host: prefix.dev
        # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    - name: build all 
      run: |
        pixi run clean
        pixi run build
        pixi run check
        pixi run docs
