name: miminal

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Test with pytest
      run: |
        pytest --version

#    - name: Install pixi
#      uses: prefix-dev/setup-pixi@v0.8.1
#      with:
#        pixi-version: v0.39.2
#        cache: true
#        # auth-host: prefix.dev
#        # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
#      run: pixi --version
#    - name: build all 
#      run: |
#        pixi run clean
#        pixi run build
#        pixi run check
#        pixi run docs
#

  
