name: miminal

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ghcr.io/prefix-dev/pixi:latest

    steps:
    - uses: actions/checkout@v2
    - name: Basics
      run: |
        pixi --version
    - name: build all 
      run: |
        pixi run clean
        pixi run build
#        pixi run check
#        pixi run docs
#

  
